# Generated by Django 4.2.1 on 2023-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_contact', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Customer_info',
                'ordering': ['-customer_name'],
            },
        ),
    ]
