# Generated by Django 4.2.1 on 2023-06-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menus.category')),
            ],
            options={
                'db_table': 'restro_orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
